// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf1h98pbOgvZ7X1IZBjlW34vQbSPNxdfY',
    appId: '1:300761456053:web:0038a00fd03b79dd1e0dfc',
    messagingSenderId: '300761456053',
    projectId: 'the-burgeon-flow',
    authDomain: 'the-burgeon-flow.firebaseapp.com',
    storageBucket: 'the-burgeon-flow.appspot.com',
    measurementId: 'G-X2NGD4CHW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnyujXk_q9Lcbn_OEMHmmxrj0tcAR3vHA',
    appId: '1:300761456053:android:45122dec62fb79861e0dfc',
    messagingSenderId: '300761456053',
    projectId: 'the-burgeon-flow',
    storageBucket: 'the-burgeon-flow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU_k8xPvlYO7FkUXcGoyUcMbUKvmOV1pk',
    appId: '1:300761456053:ios:7a49f5c220d7df111e0dfc',
    messagingSenderId: '300761456053',
    projectId: 'the-burgeon-flow',
    storageBucket: 'the-burgeon-flow.appspot.com',
    iosClientId: '300761456053-dja3hmk2ijfd9pk054149rkrkok3hjod.apps.googleusercontent.com',
    iosBundleId: 'in.theburgeon.flow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU_k8xPvlYO7FkUXcGoyUcMbUKvmOV1pk',
    appId: '1:300761456053:ios:7a49f5c220d7df111e0dfc',
    messagingSenderId: '300761456053',
    projectId: 'the-burgeon-flow',
    storageBucket: 'the-burgeon-flow.appspot.com',
    iosClientId: '300761456053-dja3hmk2ijfd9pk054149rkrkok3hjod.apps.googleusercontent.com',
    iosBundleId: 'in.theburgeon.flow',
  );
}
